### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by justcodejs** [reo7sp/tgbot-cpp#106]
CMakeLists.txt:
# CMakeList.txt : CMake project for ApplicationCpp, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)
project(ApplicationCpp)

set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build)

add_definitions(-DTGBOT_DISABLE_NAGLES_ALGORITHM) # Disable 'Nagle's algorithm'
add_definitions(-DTGBOT_CHANGE_SOCKET_BUFFER_SIZE) # Socket Buffer Size Expansion
add_definitions(-DTGBOT_CHANGE_READ_BUFFER_SIZE) # Read Buffer Size Expansion

include_directories("./include")

# Add source to this project's executable.
add_executable (ApplicationCpp "src/main.cpp")

# TODO: Add tests and install targets if needed.

Log: 
[ 50%] Linking CXX executable build/ApplicationCpp
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `main::{lambda(std::shared_ptr<TgBot::Message>)#1}::operator()(std::shared_ptr<TgBot::Message>) const':
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:7: undefined reference to `TgBot::Api::sendMessage(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, std::shared_ptr<TgBot::GenericReply>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `main::{lambda(std::shared_ptr<TgBot::Message>)#2}::operator()(std::shared_ptr<TgBot::Message>) const':
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:11: undefined reference to `StringTools::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:14: undefined reference to `TgBot::Api::sendMessage(long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, std::shared_ptr<TgBot::GenericReply>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `main':
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:17: undefined reference to `TgBot::Api::getMe() const'
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:18: undefined reference to `TgBot::TgLongPoll::TgLongPoll(TgBot::Bot const&, int, int, std::shared_ptr<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
/media/gabriele/Developer/Projects/C++/ApplicationCpp/src/main.cpp:21: undefined reference to `TgBot::TgLongPoll::start()'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
/usr/include/boost/system/error_code.hpp:206: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:208: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
/usr/include/boost/system/error_code.hpp:656: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:659: undefined reference to `boost::system::generic_category()'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
/usr/include/boost/system/error_code.hpp:686: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:689: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:701: undefined reference to `boost::system::generic_category()'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `boost::asio::error::get_system_category()':
/usr/include/boost/asio/error.hpp:230: undefined reference to `boost::system::system_category()'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `TgBot::Bot::Bot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TgBot::HttpClient const&)':
/usr/local/include/tgbot/Bot.h:45: undefined reference to `TgBot::Api::Api(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, TgBot::HttpClient const&)'
CMakeFiles/ApplicationCpp.dir/src/main.cpp.o: In function `TgBot::Bot::_getDefaultHttpClient()':
/usr/local/include/tgbot/Bot.h:78: undefined reference to `TgBot::BoostHttpOnlySslClient::BoostHttpOnlySslClient()'
/usr/local/include/tgbot/Bot.h:78: undefined reference to `TgBot::BoostHttpOnlySslClient::~BoostHttpOnlySslClient()'
collect2: error: ld returned 1 exit status
CMakeFiles/ApplicationCpp.dir/build.make:94: recipe for target 'build/ApplicationCpp' failed
make[2]: *** [build/ApplicationCpp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ApplicationCpp.dir/all' failed
make[1]: *** [CMakeFiles/ApplicationCpp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by milkpirate** [comment]
Hey @xjabr did you resolve your problem and yes , then how?
