### ISSUE TITLE
segmentation fault running the samples

### ISSUE THREAD

**Issue by dpechman** [reo7sp/tgbot-cpp#110]
I have tried to compile and run the samples on ubuntu 18.04 but it always explodes. 
am I doing right? 

daniel@lenovo:~/dev/tgbot-cpp/samples/echobot$ cmake .
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1") 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daniel/dev/tgbot-cpp/samples/echobot
daniel@lenovo:~/dev/tgbot-cpp/samples/echobot$ make -j4
Scanning dependencies of target echobot
[ 50%] Building CXX object CMakeFiles/echobot.dir/src/main.cpp.o
[100%] Linking CXX executable echobot
[100%] Built target echobot
daniel@lenovo:~/dev/tgbot-cpp/samples/echobot$ ll
total 4816
drwxr-xr-x 4 daniel daniel    4096 out  1 10:26 ./
drwxr-xr-x 9 daniel daniel    4096 out  1 09:14 ../
-rw-r--r-- 1 daniel daniel   17356 out  1 10:26 CMakeCache.txt
drwxr-xr-x 5 daniel daniel    4096 out  1 10:26 CMakeFiles/
-rw-r--r-- 1 daniel daniel    1530 out  1 10:26 cmake_install.cmake
-rw-r--r-- 1 daniel daniel     643 out  1 09:14 CMakeLists.txt
-rw-r--r-- 1 daniel daniel     137 out  1 09:14 Dockerfile
-rwxr-xr-x 1 daniel daniel 4870912 out  1 10:26 echobot*
-rw-r--r-- 1 daniel daniel    4897 out  1 10:26 Makefile
drwxr-xr-x 2 daniel daniel    4096 out  1 10:26 src/
daniel@lenovo:~/dev/tgbot-cpp/samples/echobot$ ./echobot 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Abortado (imagem do núcleo gravada)

**Comment by WildSmilodon** [comment]
The echobot expects an environment variable to be set, which contains your token. 
See line:
`string token(getenv("TOKEN"));`

Just replace it with
`string token = "your-token";`

and it will work.

**Comment by dpechman** [comment]
TKS!!!!! it works now!
