### ISSUE TITLE
TODO: Implement Telegram Bot API from 4.0 to 4.4

### ISSUE THREAD

**Issue by pan93412** [reo7sp/tgbot-cpp#112]
I would do this after I have free time `#todo`
Changelogs: <https://core.telegram.org/bots/api-changelog#august-27-2018>

**Comment by nitanmarcel** [comment]
It will be available on my fork after one max two weeks as this project seems abandoned. I'll still make a PR here :)

**Comment by pan93412** [comment]
> It will be available on my fork after one max two weeks as this project seems abandoned. I'll still make a PR here :)

Oh thanks! :)

**Comment by nitanmarcel** [comment]
All the API versions (without V4.1 and Telegram Passport) has been added on my fork at https://github.com/nitanmarcel/tgbot-cpp

You can also wait for the owner of this repo to answer my PR: https://github.com/reo7sp/tgbot-cpp/pull/116

**Comment by reo7sp** [comment]
merged
