### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by nitanmarcel** [reo7sp/tgbot-cpp#115]
Is this project still in works or was abandoned? I managed to update to Bot API V4.2 (skipped 4.1 because the Passport isn't implemented yet) and I wish I would take over the project if is possible. I'll do a PR soon after the API updates are done and I'll let you chose if you'll accept me or let me work on the project on my fork.

Thanks :)
@reo7sp

**Comment by reo7sp** [comment]
Ok, will look at it

**Comment by Spixmaster** [comment]
@nitanmarcel My project is up to date: https://github.com/Spixmaster/telegram-bot-api

**Comment by nitanmarcel** [comment]
> @nitanmarcel My project is up to date: https://github.com/Spixmaster/telegram-bot-api

Nice, even tho I stopped using any other libraries than TdLib
