### ISSUE TITLE
Sample echo bot not working.

### ISSUE THREAD

**Issue by lucasberti** [reo7sp/tgbot-cpp#12]
Hi! I'm not really familiar with boost nor with Linux development, so I'm kinda stuck here.
I'm using the sample code in the README file, but here's what happens when I execute it:

`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ptree_bad_path> >'
  what():  No such node (first_name)
Aborted (core dumped)
`

I'm not sure what is happening here. I managed to run it perfectly fine for a few times, then it started happening. I _think_ it was after a friend forwarded 3 messages in a group chat, but I'm not sure. Since then, it stopped working.

The code is the same as in [here](https://github.com/reo7sp/tgbot-cpp#samples), but with my proper token. Any help is appreciated.
Thanks!

**Comment by admetat** [comment]
This appears related to the issue I was about to post.

You won't get a first_name property for group messages.
Getting a core dump also looks as if you're not using a try-catch block.

In TgTypeParser.cpp, look for occurences like
   result->firstName = data.get<string>("first_name");
and edit to use a second parameter, the default string:
   result->firstName = data.get<string>("first_name" , "Incognito" );

The variant of ptree::get() with a default value as second parameter does not throw that exception but it is not used consistently for (according to Telegram API docs) optional data fields.

**Comment by reo7sp** [comment]
I guess this pull request #16 solved the issue
