### ISSUE TITLE
PollOption broken or deprecated?

### ISSUE THREAD

**Issue by nicholascw** [reo7sp/tgbot-cpp#127]
![图片](https://user-images.githubusercontent.com/7414442/76160304-04af3000-60f7-11ea-9035-95733100c2bc.png)
Seems the PollOption array isn't properly implemented? I was assuming it would be a pointer to a vector of PollOption object or pointing to an array of PollOption no matter it's supporting API v4.2 or v4.6, but seems it works in neither way.

**Comment by nicholascw** [comment]
![图片](https://user-images.githubusercontent.com/7414442/76168968-2550a780-6142-11ea-84ec-b9e69b2b259f.png)
btw here the stopPoll parameter list seems mismatched to the method.

**Comment by JellyBrick** [comment]
Is there any code that can reproduce this bug?
