### ISSUE TITLE
Poll's JSON assembling processing didn't properly escape quotes

### ISSUE THREAD

**Issue by nicholascw** [reo7sp/tgbot-cpp#128]
I was taking user inputs as poll option, and err `Bad Request: can't parse options JSON object` props whenever user inputs contains `""`

**Comment by ZaMaZaN4iK** [comment]
@nicholascw can you test again it with the latest commit, please?

**Comment by nicholascw** [comment]
I'll check. However I've got user inputs escaped with my own code so it may take some time.

**Comment by nicholascw** [comment]
![图片](https://user-images.githubusercontent.com/7414442/77186275-a09a4d80-6aa0-11ea-8357-b741a4cebc8b.png)
I don't think it's fixed. 
![图片](https://user-images.githubusercontent.com/7414442/77186365-c3c4fd00-6aa0-11ea-9eca-4b24f6b739e3.png)
Tested with above message, the designed behavior should be sending a poll with two options, each with string from each message after /new respectively. The previous version would give me a poll with 3 options, and the now it has the error shown in the first screenshot.
![图片](https://user-images.githubusercontent.com/7414442/77186549-0edf1000-6aa1-11ea-9fdf-4878b170a566.png)
I think it wouldn't be that hard to fix, since my commented workaround was working well.

**Comment by nicholascw** [comment]
![图片](https://user-images.githubusercontent.com/7414442/77187019-d4c23e00-6aa1-11ea-8430-b9e4b3dc48b4.png)
Also there's more test cases worth trying when debugging.
