### ISSUE TITLE
Hi everyone, i have erorrs on compilation of test, i have boost,openssl,curl but how to add this library currectly ?

### ISSUE THREAD

**Issue by ummdd** [reo7sp/tgbot-cpp#135]
Firstly Sorry of my english,
i have this errors:
Ошибка	LNK2019	ссылка на неразрешенный внешний символ "public: static class std::shared_ptr<class TgBot::InputFile> __cdecl TgBot::InputFile::fromFile(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?fromFile@InputFile@TgBot@@SA?AV?$shared_ptr@VInputFile@TgBot@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@0@Z) в функции "public: void __cdecl <lambda_82db6e495dbbaab7ac3df2cf873dfa7e>::operator()(class std::shared_ptr<class TgBot::Message>)const " (??R<lambda_82db6e495dbbaab7ac3df2cf873dfa7e>@@QEBAXV?$shared_ptr@VMessage@TgBot@@@std@@@Z)	testForCPR	C:\Users\acer\source\repos\testForCPR\testForCPR\testForCPR.obj	1

**Comment by egorpugin** [comment]
Hi,

How do you link this library?
Are you using cmake to generate VS project?

---

Build tgbot library statically, it should help.
InputFile is not exported indeed.

**Comment by egorpugin** [comment]
I've added missing TGBOT_API. But this might not help you until you try static build.
https://github.com/reo7sp/tgbot-cpp/commit/a79166516734d965032b5e94b66f1aae9f493424

**Comment by ummdd** [comment]
i just adding include path to my project in visual studio

**Comment by ummdd** [comment]
when I recompile through a relish it gives an error such 
$ cmake .
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.24.28314.0
-- The CXX compiler identification is MSVC 19.24.28314.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at D:/cmake-3.16.2-win64-x64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
  D:/cmake-3.16.2-win64-x64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  D:/cmake-3.16.2-win64-x64/share/cmake-3.16/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:40 (find_package)

**Comment by ZaMaZaN4iK** [comment]
@ummdd you should provide all required dependencies to your application. You can do it manually (but it's *not* recommended way).

I suggest you to use Conan dependency manager (https://docs.conan.io/en/latest/). Then try to use `tgbot-cpp` library from Conan (e.g. you can use my package: `tgbot-cpp/1.1@zamazan4ik/testing`).

I hope it will help you.

**Comment by brunolapastina** [comment]
@ummdd I have the same problem. Under ubuntu you can fiz this by installing libz
`sudo apt-get install zlib1g-dev`

After that I also had to install libcurl
`sudo apt-get install libcurl14-openssl-dev`

That fixed for me

**Comment by CyrusDe** [comment]
@ZaMaZaN4iK 
> I suggest you to use Conan dependency manager (https://docs.conan.io/en/latest/). Then try to use `tgbot-cpp` library from Conan (e.g. you can use my package: `tgbot-cpp/1.1@zamazan4ik/testing`).

Your package doesn't seem to exist. Is there anything i'm missing here?
I'm using the command `conan install tgbot-cpp/1.1@zamazan4ik/testing`

**Comment by ZaMaZaN4iK** [comment]
@CyrusDe I think you just forgot about adding my remote for using this package. My conan package for `tgbot-cpp` is available here: https://bintray.com/zamazan4ik/conan/tgbot-cpp%3Azamazan4ik

Before `conan install tgbot-cpp/1.1@zamazan4ik/testing` you need add my remote with the following command: `conan remote add zamazan4ik https://api.bintray.com/conan/zamazan4ik/conan`

Hope it'll help you.

**Comment by CyrusDe** [comment]
@ZaMaZaN4iK Tried the commands and it installed the dependencies but the tgbot files seem to have problems. Conan produces this log:

https://pastebin.com/DXyT029t

 Also trying to build it just using Cmake throws this error: "Error in configuration process, project files may be invalid.

**Comment by ZaMaZaN4iK** [comment]
I don't know why but CMake tries to use `pthread.h` on Windows. Didn't meet such problems before (since I don't use Windows).

**Comment by egorpugin** [comment]
@CyrusDe 
You could try my fork https://github.com/egorpugin/tgbot with other package manager (SW).
