### ISSUE TITLE
Library installation error

### ISSUE THREAD

**Issue by maxann1980** [reo7sp/tgbot-cpp#136]
Hi All, I am trying to install library but after command "make" I get an errors

In file included from /home/pi/tgbot-cpp/src/types/InputFile.cpp:1:
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:14:17: error: variable ‘TgBot::TGBOT_API TgBot::InputFile’ has initializer but incomplete type
 class TGBOT_API InputFile {
                 ^~~~~~~~~
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:16:1: error: expected primary-expression before ‘public’
 public:
 ^~~~~~
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:16:1: error: expected ‘}’ before ‘public’
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:14:27: note: to match this ‘{’
 class TGBOT_API InputFile {
                           ^
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:16:1: error: expected ‘,’ or ‘;’ before ‘public’
 public:
 ^~~~~~
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:37:12: error: ‘InputFile’ does not name a type
     static InputFile::Ptr fromFile(const std::string& filePath, const std::string& mimeType);
            ^~~~~~~~~
/home/pi/tgbot-cpp/include/tgbot/types/InputFile.h:40:1: error: expected declaration before ‘}’ token
 }
 ^
make[2]: *** [CMakeFiles/TgBot.dir/build.make:232: CMakeFiles/TgBot.dir/src/types/InputFile.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/TgBot.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

What am I doing wrong ?

**Comment by egorpugin** [comment]
Hi, there's missing header. I've added it in https://github.com/reo7sp/tgbot-cpp/commit/c378b6fb97a30175e957c8ce0bd8ad7bf5bcbe7f
Will see how CI goes. Maybe there are some other similar places.

**Comment by egorpugin** [comment]
Ok, travis ci looks good. Try the latest master.
