### ISSUE TITLE
undefined reference to `TgBot::Api::sendMessage` in Ubuntu - codebloks

### ISSUE THREAD

**Issue by A1Gard** [reo7sp/tgbot-cpp#14]
Hi @reo7sp 
try to compile this file in Ubuntu - codeblocks by this command:

`g++ main.cpp -o main -std=c++11`

but I have this errors:

> 
> /tmp/ccHNsyWI.o: In function `main::{lambda(std::shared_ptr<TgBot::Message>)#2}::operator()(std::shared_ptr<TgBot::Message>) const':
> main.cpp:(.text+0x1b0): undefined reference to `TgBot::Api::sendMessage(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, std::shared_ptr<TgBot::GenericReply> const&) const'
> /tmp/ccHNsyWI.o: In function `main::{lambda(std::shared_ptr<TgBot::Message>)#3}::operator()(std::shared_ptr<TgBot::Message>) const':
> main.cpp:(.text+0x2d9): undefined reference to `StringTools::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> main.cpp:(.text+0x38c): undefined reference to `TgBot::Api::sendMessage(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int, std::shared_ptr<TgBot::GenericReply> const&) const'
> /tmp/ccHNsyWI.o: In function `main':
> main.cpp:(.text+0x601): undefined reference to `TgBot::Api::getMe() const'
> main.cpp:(.text+0x65e): undefined reference to `TgBot::TgLongPoll::TgLongPoll(TgBot::Bot const&)'
> main.cpp:(.text+0x68b): undefined reference to `TgBot::TgLongPoll::start()'
> /tmp/ccHNsyWI.o: In function `__static_initialization_and_destruction_0(int, int)':
> main.cpp:(.text+0xecb): undefined reference to `boost::system::generic_category()'
> main.cpp:(.text+0xed5): undefined reference to `boost::system::generic_category()'
> main.cpp:(.text+0xedf): undefined reference to `boost::system::system_category()'
> /tmp/ccHNsyWI.o: In function `TgBot::Bot::Bot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> main.cpp:(.text._ZN5TgBot3BotC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5TgBot3BotC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x27): undefined reference to `TgBot::Api::Api(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /tmp/ccHNsyWI.o: In function `boost::asio::error::get_system_category()':
> main.cpp:(.text._ZN5boost4asio5error19get_system_categoryEv[_ZN5boost4asio5error19get_system_categoryEv]+0x7): undefined reference to `boost::system::system_category()'
> collect2: error: ld returned 1 exit status

please help me solve this problem

**Comment by admetat** [comment]
This is not really an issue with the library, but with you not linking to the correct libraries.
Neither boost_system and apparently not even TgBot...

IMO this issue can be closed.

**Comment by nightsuperman** [comment]
HI
I downloaded the library from https://github.com/reo7sp/tgbot-cpp for tgbot. I copied the piece of code and have the same problem. What is it? Tell me please!

**Comment by ad-metat** [comment]
The compiler call A1ard uses (g++ main.cpp -o main -std=c++11) does not specify the needed link libraries. Additionally the options _-lboost_system_ and _-lTgBot_ should be specified (you may need to take care of lowercase uppercase there) and of course the boost_system-dev package has to be installed. Good luck!

**Comment by HungryDin0saur** [comment]
I added in CMakeLists.txt line:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -lboost_system -lTgBot"), but I got the following error: 
cannot find -lboost_system
cannot find -ltgbot.
Can you tell me what I did wrong?
