### ISSUE TITLE
All Http clients are not working properly

### ISSUE THREAD

**Issue by tort-dla-psa** [reo7sp/tgbot-cpp#141]
Code:
```c++
    if(argc!= 2){
        std::cerr<<"usage: ./"<<argv[0]<<" [bot api key]\n";
        return 1;
    }

    const auto key = std::string(argv[1]);
    std::cout<<"key provided:"<<key<<"\n";
    TgBot::Bot bot(key, TgBot::BoostHttpOnlySslClient());
    bot.getEvents().onCommand("start",
        [&bot](TgBot::Message::Ptr message) {
            auto start_message = "Hello and welcome to HelloWorld bot by me!\n"
                "type /getHello to recieve greetings";
            bot.getApi().sendMessage(message->chat->id, start_message);
    });
    try {
        auto bot_uname = bot.getApi().getMe()->username;
        std::cout<< "Bot username: "<<bot_uname<<"\n";
        TgBot::TgLongPoll longPoll(bot);
        while (true) {
            std::cout<<"Long poll started\n";
            longPoll.start();
        }
    } catch (TgBot::TgException& e) {
        std::cout<<"ERROR: "<<e.what()<<std::endl;
    }
```

Boost segfaults with this backtrace, I guess there's something wrong with io_service:
>>#0  0x000000000064e23c in boost::asio::use_service<boost::asio::detail::task_io_service> (ios=...)
    at /usr/include/boost/asio/impl/io_service.hpp:40
#1  0x000000000064e094 in boost::asio::detail::resolver_service_base::resolver_service_base (this=0x918c78, io_service=...)
    at /usr/include/boost/asio/detail/impl/resolver_service_base.ipp:39
#2  0x000000000064df50 in boost::asio::detail::resolver_service<boost::asio::ip::tcp>::resolver_service (this=0x918c78, io_service=...)
    at /usr/include/boost/asio/detail/resolver_service.hpp:54
#3  0x000000000064deb6 in boost::asio::ip::resolver_service<boost::asio::ip::tcp>::resolver_service (this=0x918c50, io_service=...)
    at /usr/include/boost/asio/ip/resolver_service.hpp:87
#4  0x000000000064dc60 in boost::asio::detail::service_registry::create<boost::asio::ip::resolver_service<boost::asio::ip::tcp> > (owner=...)
    at /usr/include/boost/asio/detail/impl/service_registry.hpp:81
#5  0x000000000064dd5d in boost::asio::detail::service_registry::do_use_service (this=0x9187c0, key=..., 
    factory=0x64dc30 <boost::asio::detail::service_registry::create<boost::asio::ip::resolver_service<boost::asio::ip::tcp> >(boost::asio::io_service&)>) at /usr/include/boost/asio/detail/impl/service_registry.ipp:123
#6  0x000000000064dbec in boost::asio::detail::service_registry::use_service<boost::asio::ip::resolver_service<boost::asio::ip::tcp> > (
    this=0x9187c0) at /usr/include/boost/asio/detail/impl/service_registry.hpp:48
#7  0x000000000064db48 in boost::asio::use_service<boost::asio::ip::resolver_service<boost::asio::ip::tcp> > (ios=...)
    at /usr/include/boost/asio/impl/io_service.hpp:33
#8  0x000000000064dae1 in boost::asio::basic_io_object<boost::asio::ip::resolver_service<boost::asio::ip::tcp>, false>::basic_io_object (
    this=0x7fffffffd4a8, io_service=...) at /usr/include/boost/asio/basic_io_object.hpp:91
#9  0x000000000064a190 in boost::asio::ip::basic_resolver<boost::asio::ip::tcp, boost::asio::ip::resolver_service<boost::asio::ip::tcp> >::basic_resolver (this=0x7fffffffd4a8, io_service=...) at /usr/include/boost/asio/ip/basic_resolver.hpp:68
#10 0x000000000064983d in TgBot::BoostHttpOnlySslClient::makeRequest[abi:cxx11](TgBot::Url const&, std::vector<TgBot::HttpReqArg, std::allocator<TgBot::HttpReqArg> > const&) const (this=0x7fffffffdae8, url=..., args=std::vector of length 0, capacity 0)
    at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/net/BoostHttpOnlySslClient.cpp:21
#11 0x000000000057b454 in TgBot::Api::sendRequest (this=0x7fffffffdb48, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
method=, args=std::vector of length 0, capacity 0)
---Type <return> to continue, or q <return> to quit---
    at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/Api.cpp:1164
#12 0x000000000057b28d in TgBot::Api::getMe (this=0x7fffffffdb48) at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/Api.cpp:23

If I use CurlHttpClient, It gives me this output:
>>key provided:XXX
terminate called after throwing an instance of 'std::runtime_error'
  what():  curl error: Unsupported protocol
Program received signal SIGABRT, Aborted.

backtrace:
>>#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff60cd801 in __GI_abort () at abort.c:79
#2  0x00007ffff6ac0957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6ac6ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6ac6b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6ac6d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000665fee in TgBot::CurlHttpClient::makeRequest[abi:cxx11](TgBot::Url const&, std::vector<TgBot::HttpReqArg, std::allocator<TgBot::HttpReqArg> > const&) const (this=0x7fffffffdaf0, url=..., args=std::vector of length 0, capacity 0)
    at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/net/CurlHttpClient.cpp:65
#7  0x000000000057be94 in TgBot::Api::sendRequest (this=0x7fffffffdb48, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
method=, args=std::vector of length 0, capacity 0)
    at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/Api.cpp:1164
#8  0x000000000057bccd in TgBot::Api::getMe (this=0x7fffffffdb48) at /home/tort/files/gits/bot_example/submodules/tgbot-cpp/src/Api.cpp:23

**Comment by tort-dla-psa** [comment]
Turned out that a) I should send http client by reference and b) I have network issues. Both solved, now it works.

**Comment by yourAnonDH** [comment]
can you tell exactly how did you fixed it?
