### ISSUE TITLE
Unsafe extraction of optional fields (exception when getting messages from groups : property first_name is not present)

### ISSUE THREAD

**Issue by admetat** [reo7sp/tgbot-cpp#15]
Missing optional fields returned by Telegram are not handled safely, for example by consistently using data.get() with a default value.

Test case:
   Having the bot inside a group,
   messages do not come with a first_name field.

Results in exception because ptree::get throws if it can't find the field in calls like
   result->firstName = data.get<string>("first_name");

Solution that worked for me:
   result->firstName = data.get<string>("first_name" , "" );

**Comment by reo7sp** [comment]
I guess this pull request https://github.com/reo7sp/tgbot-cpp/pull/16 solved the issue
