### ISSUE TITLE
No Response Lately

### ISSUE THREAD

**Issue by nesc1** [reo7sp/tgbot-cpp#152]
Hi all, I have two bots in different machines and lately, they both work fine for some time, but sometimes they are getting stuck, don't really know what is happening but it seems that they get stuck on 'longPoll.start();'.

As anyone getting the same problem or it is only me.

The symptom is that it seems that the bot is working properly receiving and handling the requests from telegram clients, but meanwhile it stops handling client requests... the bot seems to be working properly because it have asynchronous tasks that are getting executed, but the commands that a user is sending thru telegram client never reaches the bot... and this is happening lately, don't know if is a server problem, don't know if is the connection that get's stuck (it seems strange that) or don't know if is on my code, that's why i'm trying to see if the problem is a public problem or is only me.

I have logs on the begining of each normal handling (noncomand, command... etc) and they are not getting called, it seems that the server connection is not returning (this is my initial analyses).

If someone can help me understand or debug the issue I will be most appreciate.

Best regards,
Nuno

**Comment by ZaMaZaN4iK** [comment]
You are not alone in the problem :) in `tgbot-cpp` there is a bug, when bots stop receiving updated from Telegram servers. The reason is in proper tweking TCP connection. @egorpugin can you more details. AFAIK he has a tgbot-cpp fork with a fix.

**Comment by egorpugin** [comment]
Hi,

I've found these settings in python bot library and it seems they are working fine.
https://github.com/egorpugin/tgbot/blob/master/src/CurlHttpClient.cpp#L35

**Comment by nesc1** [comment]
hi, humm but I'm using the default http client that is:

    static HttpClient& _getDefaultHttpClient() {
        static BoostHttpOnlySslClient instance;
        return instance;
    }

and it seems that this one is not using curl! right? so my problem is not what you refer... but probably i can try to change to curl and do what you are sugesting...

**Comment by JellyBrick** [comment]
@nesc1 
Use `-DTGBOT_DISABLE_NAGLES_ALGORITHM`

**Comment by nesc1** [comment]
@JellyBrick this is for BoostHttpOnlySslClient right?.. 

Now I'm testing with curl client... let see...if curl does not help I will  try this... 

Thank you

**Comment by nesc1** [comment]
it seems that with curl it works, so I will stick with curl solution for now.

Thanks everyone.
