### ISSUE TITLE
Call to boost::asio::read() is stuck in makeRequest() in BoostHttpOnlySslClient.cpp

### ISSUE THREAD

**Issue by rwmoekoe** [reo7sp/tgbot-cpp#160]
In TgBot library I use under MSVC++, in tgbot/net/BoostHttpOnlySslClient.cpp, in makeRequest(),
a call to boost::asio::read() does not return when internet is disconnected for a few minutes. The whole thread becomes stuck from then on even after the internet connection is back.

I would appreciate any help to get this resolved, i.e. for the read function to return if it fails after some timeout has passed

the code block in the tgbot/net/BoostHttpOnlySslClient.cpp file:

`
string BoostHttpOnlySslClient::makeRequest(const Url& url, const vector<HttpReqArg>& args) const {
    tcp::resolver resolver(_ioService);
    tcp::resolver::query query(url.host, "443");

    ssl::context context(ssl::context::tlsv12_client);
    context.set_default_verify_paths();
    ssl::stream<tcp::socket> socket(_ioService, context);
    connect(socket.lowest_layer(), resolver.resolve(query));

    #ifdef TGBOT_DISABLE_NAGLES_ALGORITHM
    socket.lowest_layer().set_option(tcp::no_delay(true));
    #endif //TGBOT_DISABLE_NAGLES_ALGORITHM
    #ifdef TGBOT_CHANGE_SOCKET_BUFFER_SIZE
    #if _M_ARM64 || _WIN64 || __amd64__ || __x86_64__ || __MINGW64__ || __aarch64__ || __powerpc64__
    socket.lowest_layer().set_option(socket_base::send_buffer_size(65536));
    socket.lowest_layer().set_option(socket_base::receive_buffer_size(65536));
    #else //for 32-bit
    socket.lowest_layer().set_option(socket_base::send_buffer_size(32768));
    socket.lowest_layer().set_option(socket_base::receive_buffer_size(32768));
    #endif //Processor architecture
    #endif //TGBOT_CHANGE_SOCKET_BUFFER_SIZE
    socket.set_verify_mode(ssl::verify_none);
    socket.set_verify_callback(ssl::rfc2818_verification(url.host));

    socket.handshake(ssl::stream<tcp::socket>::client);

    string requestText = _httpParser.generateRequest(url, args, false);
    write(socket, buffer(requestText.c_str(), requestText.length()));

    string response;

    #ifdef TGBOT_CHANGE_READ_BUFFER_SIZE
    #if _M_ARM64 || _WIN64 || __amd64__ || __x86_64__ || __MINGW64__ || __aarch64__ || __powerpc64__
    char buff[65536];
    #else //for 32-bit
    char buff[32768];
    #endif //Processor architecture
    #else
    char buff[1024];
    #endif //TGBOT_CHANGE_READ_BUFFER_SIZE

    boost::system::error_code error;
    while (!error) {
        std::size_t bytes = read(socket, buffer(buff), error);
        response += string(buff, bytes);
    }

    return _httpParser.extractBody(response);
}

`

Thankyou in advance😀🙏

**Comment by JellyBrick** [comment]
use CurlHttpClient instead of BoostHttpOnlySslClient.

**Comment by cl-ement05** [comment]
Sorry to ask this here, but I am struggling to find out what does "TOKEN" mean in the bot constructor method ? Is it your telegram api_hash or api_id ? Am i missing something ?

**Comment by rwmoekoe** [comment]
> use CurlHttpClient instead of BoostHttpOnlySslClient.

Thanks for the solution, although I haven't tried it.
I have decided not to use Curl because it failed more often such as failing to send messages or getting updates even when internet connection is stable.

An update for the problem, is that currently I'm trying a workaround using `async_read_some()` (with `async_resolve()` and `async_connect()` before it).

This works with the same exact problem as before, only this time it's stuck in `::GetQueuedCompletionStatus(()` in `do_one()`. Just the same stuck case.

```

**Comment by rwmoekoe** [comment]
Hello,Token is what BotFather gave you when you first created the bot in telegram chat with botfather.The format is something like "1234567890:abcAbc123123abcABC"On Mar 9, 2021 18:22, Clement ***@***.***> wrote:
Sorry to ask this here, but I am struggling to find out what does "TOKEN" mean in the bot constructor method ? Is it your telegram api_hash or api_id ? Am i missing something ?
