### ISSUE TITLE
Migration to the 64-bit range for IDs

### ISSUE THREAD

**Issue by phiblock-project** [reo7sp/tgbot-cpp#197]
Hello,

Is the code in this library updated for 64-bit IDs? According to the documentation, the [int32_t id](http://reo7sp.github.io/tgbot-cpp/_user_8h_source.html#l00022) type is still used.

Official announcement [ Durov's Channel  64-bit migration](https://t.me/durov/167)

**Comment by phiblock-project** [comment]
Ok, I see it is adapted. Thank you.

The documentation is not up to date, right?

https://github.com/reo7sp/tgbot-cpp/commit/3553efe53c9df0c685a58c00be71b9bb841b4c70

**Comment by JellyBrick** [comment]
yep

**Comment by reo7sp** [comment]
I have regenerated docs now
