### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by Pizza-Prime** [reo7sp/tgbot-cpp#203]
https://user-images.githubusercontent.com/82731605/173170206-88f92c3f-207b-49f9-9c43-202b9374f3f7.mp4

Not sure on how to fix these errors. Plz help

**Comment by Pizza-Prime** [comment]
I tried to do the Cmake thing.
What I did was I opened up a console project > File > Open > Cmake > I put in the Cmakelist.txt
(Not sure if I'm supposed to do that) I never used cmake before. 
![image](https://user-images.githubusercontent.com/82731605/173170877-aa6992e9-f997-47ac-8380-0f75e081953d.png)

**Comment by reo7sp** [comment]
Maybe you didn’t enabled c++11 support in visual studio.

This errors are not about tgbot-cpp library
