### ISSUE TITLE
Can't figure out about editing recently sent messages by bot

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [reo7sp/tgbot-cpp#218]
I can't find any possible method to do that in C++.

Example:
I have this part of code:
```
        bot.getApi().sendMessage(message->chat->id, "|", false, 0, 0, "Markdown", false);
        Sleep(5000);
        bot.getApi().editMessageText("/", message->chat->id, message->messageId, 0, "Markdown", false, 0);
```

Even if `message->messageId` isn't zero or something else, I still can't do that code because it sends me to [This](https://user-images.githubusercontent.com/51203385/181916441-f8187ef4-1a6a-49b4-a128-949f685225ba.png)

**Comment by llnulldisk** [comment]
The fourth parameter of editMessageText() is a string and not an int:
`bot.getApi().editMessageText("/", message->chat->id, message->messageId, "", "Markdown", false, 0);`

You are also trying to edit the command message from the user. You can only edit messages from the bot itself. You need to get the message id of the message "|" and then use this id in editMessageText()

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> You need to get the message id of the message "|" and then use this id in editMessageText()

I can't figure out how I can get it!

**Comment by llnulldisk** [comment]
Well, the sent message is returned on success with sendMessage()

```cpp
Message::Ptr sentMessage = bot.getApi().sendMessage(message->chat->id, "|", false, 0, 0, "Markdown", false);
Sleep(5000);
bot.getApi().editMessageText("/", message->chat->id, sentMessage->messageId, "0", "Markdown", false, 0);
```

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Thank you so much, it works!
