### ISSUE TITLE
New line simbol and white space in question and answer text

### ISSUE THREAD

**Issue by minigo** [reo7sp/tgbot-cpp#230]
std::string question = "1\n2\n3\n4\n5";
std::vector<std::string> options = {"False", "0", "1", "This\ncode\nhas\nan\nerror"};

![FullSizeRender](https://user-images.githubusercontent.com/7579415/191292159-10c25212-10da-4ca0-a3ac-0462ba9bd584.jpg)

**Comment by minigo** [comment]
[llnulldisk](https://github.com/llnulldisk) What about new line in question text? Шs this at all possible to do more than 3 lines?

**Comment by llnulldisk** [comment]
Sorry, I still wanted to answer here. Yes, the question text is limited to a maximum of 3 lines by Telegram. In addition, you cannot force a line break with \n in an answer option. Unfortunately, the poll question and the poll options cannot be formatted in general. Telegram simply ignores this
