### ISSUE TITLE
Exception after several hours of work

### ISSUE THREAD

**Issue by minigo** [reo7sp/tgbot-cpp#236]
I receved exception after several hours of work:

`terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  connect: Connection timed out
Aborted (core dumped)`

Is it normal?

**Comment by llnulldisk** [comment]
No, that's not normal. I ran a test bot today for 6 hours but I didn't get an error?
What does several hours mean? Does the error appear every time after several hours? Do you have more information about the error that could be useful?

**Comment by minigo** [comment]
Sorry. That was my fault

**Comment by Charles1026** [comment]
Hi, I'm facing the same issue too could you please help give some pointers on how you fixed the above issue?
