### ISSUE TITLE
About enter game

### ISSUE THREAD

**Issue by okman334** [reo7sp/tgbot-cpp#244]
I create a game by the botfather. But when I call the sendGame api, I get a error like that: Bad Request: REPLY_MARKUP_GAME_EMPTY. 
I create an InlineKeyboardButton already. Can someone give me some help? Thanks.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/58942300/204170925-1f08969c-7ac2-446f-9d26-75ce6f1499f1.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/58942300/204170957-420d6433-332d-4fda-b80e-a5e1ea879b01.png">

**Comment by llnulldisk** [comment]
According to the docs of the InlineKeyboardButton:

> You must use exactly one of the optional fields.

Currently, you use the two fields callbackData and callbackGame. If you remove the callbackData, it should work with the commit

**Comment by okman334** [comment]
I found the cause of the problem. so the code diff.
The function "parseInlineKeyboardButton"  forget to parse callback_game parameter. @reo7sp 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/58942300/204275027-8de62949-a9e3-4f2f-a9f5-fb6e7a8fc107.png">
