### ISSUE TITLE
Error compiling of example file

### ISSUE THREAD

**Issue by balebanov** [reo7sp/tgbot-cpp#25]
Hello. I have a Linux Mint 17.3. I did everything as it's written at docs. When I compiled sample programm, it gave me lots of error (in file). What should I do? Thanks
[tlg_error.txt](https://github.com/reo7sp/tgbot-cpp/files/546286/tlg_error.txt)

**Comment by Armagetron** [comment]
Hi @balebanov : could you also post the steps you did to compile the program? It seems that you are missing a -std=c++11

**Comment by balebanov** [comment]
@Armagetron 
Installation of library was successful
1. Compile: g++ telegram_bot.cpp -std=c++11
Errors in file: 
[tlg_error_new.txt](https://github.com/reo7sp/tgbot-cpp/files/546502/tlg_error_new.txt)
I also reinstalled library - the same result :(

**Comment by Armagetron** [comment]
Are you linking against the library?

**Comment by balebanov** [comment]
@Armagetron what do you mean?

**Comment by Armagetron** [comment]
You need to tell the compiler to link against the bot library.

Try something like: ```g++ -std=c++11 -lTgBot telegram_bot.cpp```

**Comment by balebanov** [comment]
I've done, but anyway there are errors :(
[error.txt](https://github.com/reo7sp/tgbot-cpp/files/548211/error.txt)

**Comment by vanbwodonk** [comment]
Hi, 
try this
```
g++ telegram_bot.cpp -o telegram_bot -std=c++11 -lTgBot -lpthread -lssl -lcrypto -lboost_system
```
I found that after verbose cmake output.

**Comment by balebanov** [comment]
@vanbwodonk thank you, I've tried this, but there are also errors
[errors.txt](https://github.com/reo7sp/tgbot-cpp/files/610193/errors.txt)

**Comment by Armagetron** [comment]
Your problem here might be, that the includes do not work as expected. Try adding -I/usr/local/include to your build line.

**Comment by Macropinna** [comment]
@balebanov add `using namespace TgBot;` or use `TgBot::Message::`

**Comment by VanyaSmyalko** [comment]
Hello, I'm using Windows OS and Visual Studio 2017. When i'm try to build it, i have an error
**1>c:\users\smyalko ivan\desktop\tgbot-cpp-master\include\tgbot\api.h(29): fatal error C1083: Cannot open include file: 'boost/property_tree/ptree.hpp': No such file or directory**
Help please.

**Comment by Armagetron** [comment]
Do you have boost installed and correctly configured so that Visual Studio finds it?

**Comment by VanyaSmyalko** [comment]
No, sorry, what is it?

**Comment by Armagetron** [comment]
[Boost](http://www.boost.org/) is one of the dependencies as stated in the README. You need it in order to compile the code.

**Comment by rafa93m** [comment]
Hello, I am trying to compile the example from Eclipse Neon in my Ubuntu 16.04 and it gives me the errors that I attach in the file [errores.txt](https://github.com/reo7sp/tgbot-cpp/files/702326/errores.txt). 
The **-std=c++11** parameter I have included and **-l /usr/local/include** as well. The only way I have succeeded is from the terminal using **g++ telegram_bot.cpp -o telegram_bot -std = c ++ 11 -lTgBot -lpthread -lssl -lcrypto -lboost_system** but does not display the words with the letter "ñ" And with the accented words, I installed the latest Boost library (version 1.63.0).
It may be obvious but I'm noob.
Thank you for your support and sorry for my bad English.

**Comment by ummdd** [comment]
Hello, I am trying to compile the example from Visual stuio and have errors like 
2>C:\Users\acer\cpp\tgbot-cpp\include\tgbot/types/InputFile.h(14):error C2825: TgBot :: InputFile: should represent a class or namespace followed by "::"
2> C: \ Users \ acer \ cpp \ tgbot-cpp \ include \ tgbot / tools / StringTools.h (71.19): error C4430: missing type specifier - int is assumed. Note. C ++ does not support int by default

**Comment by RifatMAmayusupov** [comment]
hello ........ , i have problem , please help me how to solve it
:: this is error:  Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot> cd "c:\Users\Lenovo\Desktop\codes\vazifa\elon_bot\" ; if ($?) { g++ 1.C++ -o 1 } ; if ($?) { .\1 }
1.C++:7:10: fatal error: tgbot/tgbot: No such file or directory
 #include <tgbot/tgbot>
          ^~~~~~~~~~~~~
compilation terminated.
PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot> g++ -std=c++11 -lTgBot telegram_bot.cpp
g++.exe: error: telegram_bot.cpp: No such file or directory
PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot>

**Comment by llnulldisk** [comment]
You need to specify the include path to the tgbot library, when you use g++

**Comment by APTEM591** [comment]
> hello ........ , i have problem , please help me how to solve it :: this is error: Windows PowerShell Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6
> 
> PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot> cd "c:\Users\Lenovo\Desktop\codes\vazifa\elon_bot" ; if (?)g++1.C++−o1;if(?) { .\1 } 1.C++:7:10: fatal error: tgbot/tgbot: No such file or directory #include <tgbot/tgbot> ^~~~~~~~~~~~~ compilation terminated. PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot> g++ -std=c++11 -lTgBot telegram_bot.cpp g++.exe: error: telegram_bot.cpp: No such file or directory PS C:\Users\Lenovo\Desktop\codes\vazifa\elon_bot>

Same problem, even if i specify the include path in cmakelists
