### ISSUE TITLE
how to make a telegram file accessible from public internet for downloading

### ISSUE THREAD

**Issue by yourAnonDH** [reo7sp/tgbot-cpp#256]
Hello! I was just looking for a solution to make a telegram file which user sends to bot public on the internet for downloading in purpose of making a file to link bot. Thanks for help!

**Comment by llnulldisk** [comment]
Hi!

Currently it works like this. You send for example a document to the bot. Then the bots receives a [Document](https://reo7sp.github.io/tgbot-cpp/class_tg_bot_1_1_document.html) object. You then take the [`Document::fileId`](https://reo7sp.github.io/tgbot-cpp/class_tg_bot_1_1_document.html#aa67870c6320092c13154abde7dcdf94c) of this document and save it for later. Next, you prepare the file for downloading via [`Api::getFile()`](https://reo7sp.github.io/tgbot-cpp/class_tg_bot_1_1_api.html#ac50bdd50bf0cf5a211e699925759ebc1). This function returns the [`File::filePath`](https://reo7sp.github.io/tgbot-cpp/class_tg_bot_1_1_file.html#ad1abfaf438998878eee537fc82b4bb6e) of said document. 
Remember, this `filePath` will be valid for at least 1 hour and the maximum file size to download is 20 MB.

The file is now downloadable via this link: `https://api.telegram.org/file/bot<token>/<filePath>`

**Comment by yourAnonDH** [comment]
So there is no way to upload a file to else where without downloading it?

**Comment by llnulldisk** [comment]
Not that I know of. The only thing that spontaneously comes to mind is that you're not downloading the file via the link but via [`Api::downloadFile`](https://reo7sp.github.io/tgbot-cpp/class_tg_bot_1_1_api.html#aa60ec06b9171d94ef717f1ac03190f07). The function returns the file content as a string. Then you have the content and can upload it to another server as you like.

**Comment by yourAnonDH** [comment]
okay man, thanks to you!
