### ISSUE TITLE
how to specify message type

### ISSUE THREAD

**Issue by yourAnonDH** [reo7sp/tgbot-cpp#259]
Hello! I just want to know how can we know if a user send a video or image or text? how to do that? thanks!

**Comment by MrVolot** [comment]
TgBot::Message::Ptr message has all of the things that you mentioned (video, photo, voice, etc). Tou can access it by message->photo, for example. If you want to check what is present, you can check what is empty.

**Comment by yourAnonDH** [comment]
@MrVolot Thanks! I want to to make a bot to download files that user sends to it and save them to memory, do you know how to do this? or is there any example codes for this?

**Comment by MrVolot** [comment]
You can check it here: https://stackoverflow.com/a/32679930. The API calls that are mentioned there are implemented as methods in this library.
