### ISSUE TITLE
libssl error on debian

### ISSUE THREAD

**Issue by miannoodle01** [reo7sp/tgbot-cpp#260]
Hello! I just wrote my bot and on testing it on my debian 10 buster vps it throwed this error:
_error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory_

**Comment by llnulldisk** [comment]
Hi!

How did you install OpenSSL? Does it help if you reinstall it with `sudo apt install --reinstall libssl-dev `

**Comment by yourAnonDH** [comment]
@llnulldisk 

Was already installed, and server expired so...

**Comment by yourAnonDH** [comment]
all done! just need to install normal libssl not dev
