### ISSUE TITLE
How to skip old messages?

### ISSUE THREAD

**Issue by serhiops** [reo7sp/tgbot-cpp#267]
I saw [this issue](https://github.com/reo7sp/tgbot-cpp/issues/231) but i don't understand how to skip updates while bot is unactive

**Comment by bartcubbins** [comment]
https://github.com/reo7sp/tgbot-cpp/blob/c9ebca67ba33cc2e132cc19e51d52ec2d275fac1/include/tgbot/Api.h#L114
