### ISSUE TITLE
Clean Tg Update queu

### ISSUE THREAD

**Issue by jiren85** [reo7sp/tgbot-cpp#301]
Hello,

I've a question;
Is there in your lib a method to clean the telegram updates queue after I've received the update?

Thank you in advance.

Regards

**Comment by llnulldisk** [comment]
Hi,

The update is automatically cleaned from the queue, if you handle it.

Do you want to discard all pending updates in the queue? Then no, there is currently no such function. However, you can do something like this:

```
Update::Ptr update = api.getUpdates(-1).front();
api.getUpdates(update->updateId + 1);
```

-------- Ursprüngliche Nachricht --------
Am 05.05.24 12:47 um jiren85 schrieb :

**Comment by jiren85** [comment]
Great It's perfect.

Thank you so much.
