### ISSUE TITLE
Crashing after checking type of media

### ISSUE THREAD

**Issue by pryaneque** [reo7sp/tgbot-cpp#324]
Hello!
I'm trying to write a bot with feature of analyzing different types of messages and collect them. I tried to find something similar to `getEvents().onCallbackQuary()`, but no result. 

Now I do it like (and it works):

```
bot.getEvents().onAnyMessage([&bot](TgBot::Message::Ptr message) {
        if (!(message->photo.empty())) { 
            func1();
        }
        else {
            if (message->text != "") {
                func2();
            }
            else {
                if (message->video->fileId != "") {
                    func3();
                }
            }
        }      
    });
```

I can't analyze it parallel (if1, if2, if3), only jumping from if to else and deeper... Is it only one solution in my situation or there any instruments in library to solve my problem?

If I realize if1, if2, if3, I'll get 99% crash of program. Because when I getting photo and doing `if (message->video->fileId != "")` program crashes.

**Comment by reo7sp** [comment]
> Is it only one solution in my situation or there any instruments in library to solve my problem?

Just use debugger (gdb or any other).

**Comment by pryaneque** [comment]
Thank you for your response!
