### ISSUE TITLE
TG gives Error 1: handshake: unknown protocol with openssl-libs-1.0.1e-60.el7

### ISSUE THREAD

**Issue by shured** [reo7sp/tgbot-cpp#34]
Afterdowngrading to 1e-51 it works again. I'd like a more permanent solution.

**Comment by Armagetron** [comment]
Can you give some more information on what changed from openssl-libs-1.0.1e-51.el7 to openssl-libs-1.0.1e-60.el7?

Try setting [Line 39](https://github.com/reo7sp/tgbot-cpp/blob/master/src/net/HttpClient.cpp#L39) to 
```
ssl::context context(ssl::context::tlsv12);
```
Does this work with the new library version?
