### ISSUE TITLE
parseJsonAndGetGenericReply is used or can be delete?

### ISSUE THREAD

**Issue by ymuv** [reo7sp/tgbot-cpp#35]
**GenericReply::Ptr TgTypeParser::parseJsonAndGetGenericReply(const boost::property_tree::ptree& data) const** function isn't used anywhere. Also it  has control reaches end of non-void function.

**Comment by reo7sp** [comment]
I think this method should not be deleted so that consistency `type <-> parse methods` for each telegram type won't be broken
