### ISSUE TITLE
Bot API 3.0 support.

### ISSUE THREAD

**Issue by ghost** [reo7sp/tgbot-cpp#48]
Refer to Bot API changelog: https://core.telegram.org/bots/api-changelog

**Payment Platform**

See Introduction to Bot Payments for a brief overview. If you're not a developer, you may like this user-friendly blog post better.
- [ ]    Added new kinds of updates, shipping_query and pre_checkout_query, and new types of message content, invoice and successful_payment.
- [ ]    Added new methods for payments: sendInvoice, answerShippingQuery, and answerPreCheckoutQuery.
- [ ]    Added a new type of button, the pay button to InlineKeyboardButton.

**Video Messages**
- [x]    Added the sendVideoNote method, the new field video_note to Message, the fields record_video_note or upload_video_note to sendChatAction.

**Multilingual Bots**
- [x]    The User object now may have a language_code field that contains the IETF language tag of the user's language.

**More power to admin bots**
- [x]    ~~New method deleteMessage that allows the bot to delete its own messages, as well as messages posted by other in groups and channels where the bot is an administrator.~~

**Minor Changes**
- [x]    Replaced the field new_chat_member in Message with new_chat_members (the old field will still be available for a while for compatibility purposes).
- [x]    New fields gif_duration in InlineQueryResultGif and mpeg4_duration in InlineQueryResultMpeg4Gif.

**Comment by foxcpp** [comment]
I'm working on Payments API now.
You can check [`botapi3-payments`](https://github.com/foxcpp/tgbot-cpp/tree/botapi3-payments) branch of my fork.
