### ISSUE TITLE
`HttpParser` uses `std::string` concatenation to build http request body. Would be better to use `std::stringstream`

### ISSUE THREAD

**Issue by fnc12** [reo7sp/tgbot-cpp#49]
In `net/HttpParser.cpp` such a code can be found:

```c++
string HttpParser::generateRequest(const Url& url, const vector<HttpReqArg>& args, bool isKeepAlive) {
	string result;
	if (args.empty()) {
		result += "GET ";
	} else {
		result += "POST ";
	}
	result += url.path;
	result += url.query.empty() ? "" : "?" + url.query;
	result += " HTTP/1.1\r\n";
	result += "Host: ";
	result += url.host;
	result += "\r\nConnection: ";
	if (isKeepAlive) {
		result += "keep-alive";
	} else {
		result += "close";
	}
	result += "\r\n";
	if (args.empty()) {
		result += "\r\n";
	} else {
		string requestData;

		string bondary = generateMultipartBoundary(args);
		if (bondary.empty()) {
			result += "Content-Type: application/x-www-form-urlencoded\r\n";
			requestData = generateWwwFormUrlencoded(args);
		} else {
			result += "Content-Type: multipart/form-data; boundary=";
			result += bondary;
			result += "\r\n";
			requestData = generateMultipartFormData(args, bondary);
		}

		result += "Content-Length: ";
		result += lexical_cast<string>(requestData.length());
		result += "\r\n\r\n";
		result += requestData;
	}
	return result;
}
```

It's not the best practice to concatenate strings cause it can spend more time than `std::stringstream` from `<sstream>` header with `operator<<`.

**Comment by naveenvhegde** [comment]
Hi, 

std::stringstream is slower than normal string concatenation. 
https://stackoverflow.com/questions/18892281/most-optimized-way-of-concatenation-in-strings

**Comment by fnc12** [comment]
Hm. Interesting. Thanks.

**Comment by naveenvhegde** [comment]
std::stringstream is extremely useful when you have concrete classes to be logged and most of the classes overloads operator <<.

Also sometimes is it used to typecast double, int, long to string - instead of using strtod, strtol (These are unsafe and non-reentrant)

**Comment by fnc12** [comment]
@naveenvhegde why `std::stod` and `std::stol` are unsafe?

**Comment by naveenvhegde** [comment]
These has const-laundering issues - https://stackoverflow.com/questions/993700/are-strtol-strtod-unsafe

**Comment by fnc12** [comment]
Ah ok. I thought you're talking about `std::stod` and `std::stol`.
