### ISSUE TITLE
Windows Build (msvc, vcpkg, nuget)

### ISSUE THREAD

**Issue by Thalhammer** [reo7sp/tgbot-cpp#50]
Are there any plans to provide easy build support for windows?
Also packaging for vcpkg and nuget would be really cool.
I develop most of my applications on windows using visual studio and run them on a linux.
I have created a visual studio project in my [fork](https://github.com/Thalhammer/tgbot-cpp) but I consider it far from perfect because it is not automatically in sync with the source, you have to add new files manually.
It would be much better to generate the vs project using cmake or something like this.

**Comment by foxcpp** [comment]
CMake already have generator for VS projects.
Try `cmake -G`.
