### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type int

### ISSUE THREAD

**Issue by QuantScientist** [reo7sp/tgbot-cpp#55]
Using OSX with Cmake 3.10, boost 1.64, while reading the image in the Photo example. 
![main_cpp_-_echobot_-___volumes_1tb-ext_2019_db_stan_dropbox_dev2_cpp_bots_tgbot-cpp-master_samples_echobot_](https://user-images.githubusercontent.com/18743986/35534420-25dbe1e4-0549-11e8-9b6f-91e1f2e70126.jpg)

**Comment by foxcpp** [comment]
https://github.com/reo7sp/tgbot-cpp/blob/4d9e96d9c91e1faeefb67de2164c026f84be020e/src/tools/FileTools.cpp#L22

Phew, reo7sp's crazyness.

Following code can give human-readable error message. 
```cpp
#include <stdio.h>

// ...

try {
  bot.getApi().sendPhoto(...)
} catch (int errno) {
  std::cout << strerror(errno) << '\n';
}
```

**Comment by QuantScientist** [comment]
![main_cpp_-_echobot_-___volumes_1tb-ext_2019_db_stan_dropbox_dev2_cpp_bots_tgbot-cpp-master_samples_echobot_](https://user-images.githubusercontent.com/18743986/35535243-a45913dc-054b-11e8-942e-2c13d529f82f.jpg)

**Comment by QuantScientist** [comment]
Anyone ...?

**Comment by foxcpp** [comment]
Make sure you have `example.jpg` (or other file specified in `photoFilePath`) in current working directory and it's readable.

**Comment by foxcpp** [comment]
@QuantScientist, is your problem solved? Can we close this issue (if so, please do it)?
