### ISSUE TITLE
Receiving voice notes

### ISSUE THREAD

**Issue by rsalinas** [reo7sp/tgbot-cpp#57]
Is the reception of voice notes supported? 
`mesage->voice ` seems to be always  null. 

Thanks.

**Comment by zs6lmg** [comment]
I am encountering the same issue, checked under document and audio, it is like the voice note disappeared.

Thanks

**Comment by JellyBrick** [comment]
@zs6Img I checked the `TgTypeParser`.

As you said, the `Voice` parser was not implemented, and the `message->voice` object was **always** _null_ .

**Comment by zs6lmg** [comment]
I have added the functionality, busy testing, will let you know.
