### ISSUE TITLE
Use curl instead of own HttpClient

### ISSUE THREAD

**Issue by egorpugin** [reo7sp/tgbot-cpp#72]
Hi,

Probably using curl for web requests could be more profit.
E.g. it could use proxies to overcome any telegram blocking issues.

I'd like to try to prepare a PR with such changes.
Is they welcome?

**Comment by stolyarchuk** [comment]
it wont work. mtproxy is not http proxy.
httpclient is made via boost asio, while curl is synchrous.

**Comment by reo7sp** [comment]
Yeah, I think it's great to provide curl as additional "driver" for HttpClient.

I think it's good to make this that way:
1. Rename current `HttpClient` class  to `BoostHttpClient`.
2. Make interface `HttpClient` with one function:
```cpp
std::string makeRequest(const Url& url, const std::vector<HttpReqArg>& args);
```
3. Develop your idea as class `CurlHttpClient`.
4. Add parameter `httpClientDriver` with type `HttpClient` with default value `BoostHttpClient::getInstance()` to `Bot`'s [constructor](https://github.com/reo7sp/tgbot-cpp/blob/master/include/tgbot/Bot.h#L42).

**Comment by egorpugin** [comment]
See https://github.com/reo7sp/tgbot-cpp/pull/73

**Comment by Artalus** [comment]
What are the reasons to continue supporting ASIO-powered HTTP client? Curl sounds superior in all aspects but "yet another dependency". :thinking: Is it a mere _"providing a `HttpClient` to `Api` sounds like a nice IoC move, and hey, there will be two implementations for it already!"_ or am I missing something?

**Comment by egorpugin** [comment]
At the moment the PR covers co-existence of curl and thus a selector to Api without broken user code.
Maintainers later could decide to drop boost http client completely.

**Comment by reo7sp** [comment]
Merged
