### ISSUE TITLE
BoostHttpOnlySslClient: ssl error

### ISSUE THREAD

**Issue by kyoto44** [reo7sp/tgbot-cpp#76]
everytime im trying to compile and after start i getting this

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  handshake: wrong version number

**Comment by ZaMaZaN4iK** [comment]
I think here we have some Boost issues. I think upgrading Boost version should solve the problem.
