### ISSUE TITLE
Curl timeout is not implemented

### ISSUE THREAD

**Issue by nilhcraiv** [reo7sp/tgbot-cpp#82]
I see that there is not a TIMEOUT implemented in libcurl. I think this can generate problems if the connection is lost. I'm right? It would be as follows:

```
/* For example, complete within 20 seconds */
curl_easy_setopt(curl, CURLOPT_TIMEOUT,20L);
```
In the next line to this:

https://github.com/reo7sp/tgbot-cpp/blob/5a1bcfdddecaba039e458c957f79ecc60d12a5fb/src/net/CurlHttpClient.cpp#L75

**Comment by egorpugin** [comment]
You shout set needed timeout.
CurlHttpClient provides only minimal setup for requests.
Anything else is up on you.

**Comment by nilhcraiv** [comment]
@egorpugin Thanks for your answer but, what do you mean with "Anything else is up on you"? How Can I set up a timeout to prevent it from waiting forever?

**Comment by egorpugin** [comment]
You create object of CurlHttpClient, setup it, then pass to Api object.

**Comment by nilhcraiv** [comment]
@egorpugin  Yes but we are talking about tgbot-cpp... I do not understand you. Why do not we include the timeout inside the tgbot-cpp code?

**Comment by egorpugin** [comment]
Someone does not want timeouts.
curlSettings were made public for you case, when you setup curl client as you want.
https://github.com/reo7sp/tgbot-cpp/blob/5a1bcfdddecaba039e458c957f79ecc60d12a5fb/include/tgbot/net/CurlHttpClient.h#L61

**Comment by nilhcraiv** [comment]
Can you write to me an example of timeout? Thanks!

**Comment by egorpugin** [comment]
Your wrote it in the first post.
Add your line between these lines.
https://github.com/reo7sp/tgbot-cpp/blob/master/samples/echobot-curl-client/src/main.cpp#L15

**Comment by nilhcraiv** [comment]
thanks!! I thought that I must change it inside the tgbot code. I did not know this 

> Bot bot (token, curlHttpClient); 

Thanks a lot.
