### ISSUE TITLE
Unresponsive bot - Bot does not reply back

### ISSUE THREAD

**Issue by rvalvekar** [reo7sp/tgbot-cpp#91]
I have an echobot which is running on an ARM Board. The bot application simply gets updates and reply's back to the messages or commands that are received at the bot. 
The bot is continuously running without any crashes or interruptions. When i try to send any command, the bot does not reply back anything.
I am not sure what is the correct term, but is there any timeout of the bot, which can be disabled so that the bot can run indefinitely ?  Since it is an ARM board, and running headless, there is no chance to figure out what exactly is going on.

Some more Details : 
1. A script which invokes the application is in rc.local
2. The Bot runs for first few hours, and then after couple of hours of dormancy, the bot is unresponsive. The bot does not freezes, but i guess does not get any updates.

Any possible solution that i need to implement inorder to make sure that the bot is getting the updates ?

**Comment by rvalvekar** [comment]
> Maybe your problem is caused by memory leaks.

I am using the echobot sample, provided with tgbot.

**Comment by Spixmaster** [comment]
As i am more experienced now i can tell you some possible causes:

- you marked something in the cmd window.
- the ip changes

Do you even still have the problem?

**Comment by rvalvekar** [comment]
At 

> As i am more experienced now i can tell you some possible causes:
> 
> * you marked something in the cmd window.
> * the ip changes
> 
> Do you even still have the problem?

Thanks. As of this moment it is working fine. I reinstalled the Library again, and it is working okay now.

**Comment by Spixmaster** [comment]
@rvalvekar The problem lies withing the http client. As soon as the connection is cut due to nat ip change for example the bot does not respond anymore. Try my repo instead: https://github.com/Spixmaster/telegram-bot-api
