### ISSUE TITLE
Get the join message?

### ISSUE THREAD

**Issue by Spixmaster** [reo7sp/tgbot-cpp#97]
Is it possible to get the join message?

**Comment by JellyBrick** [comment]
Yes. It's possible.

**Comment by Spixmaster** [comment]
I already searched on the internet and found no solution. How do you do it?

**Comment by Spixmaster** [comment]
With onAnyMessage() the string of the join message is empty.

**Comment by Spixmaster** [comment]
In this case i need the user who added the others.

**Comment by Spixmaster** [comment]
I already know new_chat_members but I need the person who added the users or the whole join message as a string.

**Comment by Spixmaster** [comment]
I have the solution: with `message.from()` you get the person who added the new members and with `message.newChatMembers()` you get the added users.
